POST http://localhost/fin_manage/api_finmanage/routes/incomeRoutes.php
Content-Type: application/json

{
    "action": "createIncome",
    "amount": 500,
    "description": "Salário",
    "date": "2024-09-09",
    "users_id": 7,
    "category_id": 1
}

###
POST http://localhost/fin_manage/api_finmanage/routes/incomeRoutes.php
Content-Type: application/json

{
    "action": "updateIncome",
    "id": 4,
    "amount": 750,
    "description": "Aluguel",
    "category_id" : 1
}
###
POST http://localhost/fin_manage/api_finmanage/routes/categoriesRoutes.php
Content-Type: application/json

{
    "action": "createCategory",
    "name": "Freelancer",
    "description": "Empresa talentum",
    "type": "income",
    "users_id": "10"

}

###
GET http://localhost/fin_manage/api_finmanage/routes/categoriesRoutes.php?type=income

Content-Type: application/json